// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtc2DeNNLnEXEhL_NROZxD-DxbqU8aW4E',
    appId: '1:15035334254:web:88fe15270c6127dfe3f07f',
    messagingSenderId: '15035334254',
    projectId: 'crownless',
    authDomain: 'crownless.firebaseapp.com',
    storageBucket: 'crownless.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHbv_Gl3gTQdVr8g4KKHljNSj_lOw2A7M',
    appId: '1:15035334254:android:f101cf4243cd0f53e3f07f',
    messagingSenderId: '15035334254',
    projectId: 'crownless',
    storageBucket: 'crownless.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcIeplFsrB4D9L2VguzWYA1x7FKo2FsZA',
    appId: '1:15035334254:ios:ef665bd88a82eec7e3f07f',
    messagingSenderId: '15035334254',
    projectId: 'crownless',
    storageBucket: 'crownless.firebasestorage.app',
    iosBundleId: 'com.example.crownlessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcIeplFsrB4D9L2VguzWYA1x7FKo2FsZA',
    appId: '1:15035334254:ios:ef665bd88a82eec7e3f07f',
    messagingSenderId: '15035334254',
    projectId: 'crownless',
    storageBucket: 'crownless.firebasestorage.app',
    iosBundleId: 'com.example.crownlessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtc2DeNNLnEXEhL_NROZxD-DxbqU8aW4E',
    appId: '1:15035334254:web:764776e91566ef5ae3f07f',
    messagingSenderId: '15035334254',
    projectId: 'crownless',
    authDomain: 'crownless.firebaseapp.com',
    storageBucket: 'crownless.firebasestorage.app',
  );
}
